language: node_js
node_js:
- 12
install:
- npm i -g npm@5.8.0
- npm ci
branches:
  only:
  - master
  - "/v\\d+\\.\\d+\\.d+$/"
cache:
  directories:
  - "$HOME/.npm"
stages:
- PR checks ✅
- name: "Ship It \U0001F6A2"
  if: branch=master AND type=push
jobs:
  include:
  - stage: PR checks ✅
    env:
    - NAME=Unit Tests
    script: npm run test
    after_script:
    - codecov
  - stage: PR checks ✅
    env:
    - NAME=Validation Checks
    script: "./.travis/validate_changes_for_merge.sh"
  - stage: "Ship It \U0001F6A2"
    env:
    - NAME=Publish
    script: semantic-release
notifications:
  webhooks: https://www.travisbuddy.com/
  hipchat:
    rooms:
      secure: jLi64vC05Chtjofdqs2GwdsIoZJn2OE8Nk+TBqRGwAWkRQ6UVP9kbyxZYTB7y0Jr60x2grUs9m3sQycjZrAy0Me4ge+pfAuVhim98RiAVOUPeQGRJujXoIAR4xpB8FTMsmW3vGuAz5v5cq+jKm0i6c4/5Jqn7wPkGCVYDUApmriRKuMgKsbx8FSC4kYWsRBaDEOuFU2P8LiMHaJTVZVEhnSKlJelyi8CYK7if5U82A501kuYYFbDgd24BQunkFsKL881YZ7hBjnY/JzMIXxGfLtIyUq61SQQjpu1ccum9nw+8DoJ52jTFTulgfrLupi3InOKaRzjq1POnGiZyrXEedGCWvH4lb61fKlL9OYp5yExvPlClsdwLFq+3EZhwWkquWeCftvTECdjIX6k2wFCaFl9VnkF8RCPfQioVKdE2qk8mEUsQHIjEt/84q/qoJGl5pgw97sS/+JkYmB4eytrSFwP6H9uDrRRutAp2EMHPbmYUTvWeDEOwjaHLb1iChvkkxMDydY2bO1EHWrLXl0R4QT8lOub7WRKQywgtopNLJWc+FZtntOjb5YX7rLnrFSXH/G2nczSvWScNOzqNrXzS/y1SvDoFw2dm1gO8RXhYwwYPJPqLAmFMXEClAdScPehWn8qG9YV1KI/L1PTktYX4RxCUjSKbOMDZi4vP984fdo=
env:
  global:
  # NPM_TOKEN
  - secure: hyP3JOMcU7Kpda0zxyo+qgTkclFpk7cU5J1KrilVQe4hidwJHKMdLjo00+4Pa7E3QwWqWwTblyO1k/l2mCHGoz2oA6MBUPjEimXR9CTvaxf5NOVS0vmBIYErorO7IaFKXlylXpwOKIETumHr9Uc51S0Eii9lxF9pU8h98MYTUWcOY1HdlSvotXQJi/z66WGAL3NWy8k72Y0R1XIfvnCOijYUHz0/kZJvmHHm7Cb2luEh+c7bOKWlpCN2rEcN5p/v/qo54bG+ZsejmKyguzrV9Pn5BV0GtCtKu33T8g7TZMS9dUilER/LCaG5Z1EarKQ2zdn4avHlP3RgHwE7w4EZuSIG5kQo2MKxkRKeeae8XX0UlgEru81n3IAZgKbviKVYiorV0OihxKXUQxSD0Jw0Bv2wYkLKFoxaJxMZPAdlpaOmkt0zGfNsEOrM/Z80fAF41s47nVzdyk7Zk4noVfK7/3qzejT9DG5K/aR6NSC2bY6MQHoRWqZKW8pa+kfToaC+zvh2tB2ohsHrPJX3H+OodS65Qw1Qh7kBQRIY9Sqn+mCTqMmfTGRbn8v64kLoMn2SbpZYIOeaN5UWGLsOtdw0LetnfdOBGMgkIi0CwTZ9jKnqo4dGmyX5AYH9WP/yzuyBCDZjSA1rVg5OUyQN0KyU/Yj4tKwuuC1rdyueSiguiBw=
  # GH_TOKEN
  - secure: hGJS1dCalL3yD9vU47P7GJAnHRGFmMUsYQnXXDrcu9LthNG228UuXJKrPBSElBoxu+g22NTBekHexG5rlJJ2ERRvynmdzCxc2XfQwydODf44xGqm19j/JL0cY/zTyi72daRubikFdEjEcsdKpAiMDpPk6E5Y+3RdrB34jba7lSEQiBqrkh4MnRgyouSuH/fI8Slj2L0dUDtyVtLnV89kFbgMImnh0Zvnk4H4xsN95mWvjwJQ6Dn6vSmptsfTDdGNstQRQc1lHV+RLVGtAL5hP+e8Wgh08M60ocXhE7tV00HgIWhsZTeESEJTsIlg77xFh2Ape8vGwLuI0+CR59i6qYJWuGzUqRcKdem53tcFU3eNXIiNIMZ5h9jHVxKChr3pYT2cYs1sNloF1xGkxhpctXVZ6KE/ghnww9QK6s33ouXHJI2GqatlBV8JTcVrJdRxkGFrcqdGZoC+bx10qVn38ib6zghH9Op9ZzQt5cJ8jL5JHmtz6DgfQQ4Y/INd41ExkVkJ0cllU4j+3CCZ4mPMHmluoM6oGl6S3Etxvv15EHyMMVACTwLiJGq8DTR5PtJ4Iv6sZNVvmDzyCdJmKwpFYZ46VJJxXMpifyndw8hUL0Ustskv4/wHFDmpZJMh21X0dOfd6aZ+QcuB5aZX3Eo0Cnyn+hGGao4cpMkYCxHZPSc=
